name: Trigger Self-Hosted Runner

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: arc-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print greeting
        run: echo "Hello from GitHub Actions runner!"
