apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner
  namespace: arc-runners
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::819340487192:role/GitHubSelfHosted-Lambda-Role
