githubConfigUrl: https://github.com/ssdaggupati/lambda-project
githubConfigSecret: controller-manager

maxRunners: 5
minRunners: 0
runnerGroup: "default"

template:
  metadata:
    labels:
      app.kubernetes.io/instance: arc-runner-set
  spec:
    serviceAccountName: github-runner
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        securityContext:
          privileged: true
          runAsUser: 1001
          runAsGroup: 0
        env:
          - name: DISABLE_RUNNER_UPDATE
            value: "false"
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
    volumes:
      - name: work
        emptyDir: {}

serviceAccount:
  create: true
  name: github-runner
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::819340487192:role/GitHubSelfHosted-Lambda-Role
