name: Build Lambda Deployment Package

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies and prepare Lambda package
      run: |
        mkdir -p lambda_build
        pip install -r requirements.txt -t lambda_build/
        cp lambda_function.py lambda_build/

    - name: Zip deployment package
      run: |
        cd lambda_build
        zip -r ../lambda.zip .

    - name: Upload Lambda package as artifact
      uses: actions/upload-artifact@v3
      with:
        name: lambda-package
        path: lambda.zip
